import type { Metadata } from "next";
import { getSettings } from "@/infrastructure/repositories/content-repository";
import { PublicShell } from "@/components/public-shell";
import { ConsultationForm } from "@/components/consultation-form";
import { Reveal } from "@/components/ui/reveal";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Contacto", description: "Solicite una evaluación confidencial con el Estudio Jurídico Josué Álvarez." };
export default async function ContactPage(){const settings=await getSettings();return <PublicShell settings={settings}><main><section className="page-hero"><div className="container-shell"><Reveal><span className="eyebrow" style={{color:'var(--gold)'}}>Consulta privada</span><h1>Todo caso importante empieza con una conversación clara.</h1></Reveal></div></section><section className="section-pad"><div className="container-shell contact-page-grid"><Reveal><h2 className="section-title" style={{fontSize:'clamp(46px,5vw,70px)'}}>Cuéntenos qué está en juego.</h2><p style={{color:'#606762',lineHeight:1.8}}>Comparta únicamente la información inicial necesaria. El envío de este formulario no crea por sí solo una relación abogado-cliente.</p><div className="contact-details"><div className="contact-detail"><span>Correo</span><p>{settings.email}</p></div><div className="contact-detail"><span>Teléfono</span><p>{settings.phone}</p></div><div className="contact-detail"><span>Atención</span><p>{settings.address}</p></div></div></Reveal><Reveal delay={.08}><ConsultationForm/></Reveal></div></section>{settings.map_embed_url&&<section className="location-section"><div className="container-shell location-grid"><Reveal><span className="eyebrow" style={{color:'var(--gold)'}}>Visítenos</span><h2 className="section-title">{settings.map_title}</h2><p>{settings.address}</p></Reveal><Reveal delay={.08} className="map-frame"><iframe src={settings.map_embed_url} title={settings.map_title} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /></Reveal></div></section>}</main></PublicShell>}
