import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { getRequestSession } from "@/lib/auth";
import { db } from "@/infrastructure/database/postgres";
const schema=z.object({firm_name:z.string().min(3),short_name:z.string().min(2),eyebrow:z.string(),hero_title:z.string().min(8),hero_description:z.string().min(10),about_title:z.string().min(8),about_text:z.string().min(10),about_eyebrow:z.string().min(2).max(100),primary_color:z.string().regex(/^#[0-9a-f]{6}$/i),accent_color:z.string().regex(/^#[0-9a-f]{6}$/i),logo_url:z.string().nullable().optional(),logo_media_id:z.string().uuid().nullable().optional(),about_image_media_id:z.string().uuid().nullable().optional(),email:z.string().email(),phone:z.string(),whatsapp:z.string(),address:z.string(),map_embed_url:z.string().max(2500),map_title:z.string().max(180),instagram:z.string(),linkedin:z.string()});

function normalizeMapEmbed(value:string){const raw=value.trim();if(!raw)return "";const match=raw.match(/src=["']([^"']+)["']/i);const candidate=(match?.[1]||raw).replaceAll("&amp;","&");const url=new URL(candidate);if(url.protocol!=="https:")throw new Error("El mapa debe usar una dirección HTTPS.");const allowed=["google.com","googleusercontent.com","openstreetmap.org","mapbox.com"];if(!allowed.some((domain)=>url.hostname===domain||url.hostname.endsWith(`.${domain}`)))throw new Error("Use un mapa embebido de Google Maps, OpenStreetMap o Mapbox.");return url.toString()}

export async function PUT(request:NextRequest){if(!await getRequestSession(request))return NextResponse.json({error:'No autorizado'},{status:401});try{const s=schema.parse(await request.json());const mapEmbed=normalizeMapEmbed(s.map_embed_url);await db`update public.site_settings set firm_name=${s.firm_name},short_name=${s.short_name},eyebrow=${s.eyebrow},hero_title=${s.hero_title},hero_description=${s.hero_description},about_title=${s.about_title},about_text=${s.about_text},about_eyebrow=${s.about_eyebrow},primary_color=${s.primary_color},accent_color=${s.accent_color},logo_url=${s.logo_url??null},logo_media_id=${s.logo_media_id??null},about_image_media_id=${s.about_image_media_id??null},email=${s.email},phone=${s.phone},whatsapp=${s.whatsapp},address=${s.address},map_embed_url=${mapEmbed},map_title=${s.map_title},instagram=${s.instagram},linkedin=${s.linkedin},updated_at=now() where id=true`;return NextResponse.json({ok:true})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Datos inválidos'},{status:400})}}
