"use client";
/* eslint-disable jsx-a11y/label-has-associated-control, react-hooks/set-state-in-effect */

import Link from "next/link";
import { BriefcaseBusiness, CalendarDays, ChevronRight, Eye, FileText, Image as ImageIcon, Inbox, LayoutDashboard, LoaderCircle, LogOut, Mail, MapPin, Pencil, Plus, Save, Settings, Trash2, Upload, Users, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { ElementType, ReactNode } from "react";
import { BrandMark } from "@/components/brand-mark";
import type { Article as ArticleType, EmailTemplate, Inquiry, Lawyer, MediaAsset, PracticeArea, SiteSettings, SmtpSettings } from "@/core/domain/entities";

type AdminUser = { id: string; email: string; full_name: string; role: "owner" | "admin" | "editor"; active: boolean; last_login_at: string | null; created_at: string };
type Session = { userId: string; email: string; fullName: string; role: "owner" | "admin" | "editor" };
type DashboardData = { session: Session; settings: SiteSettings; lawyers: Lawyer[]; articles: ArticleType[]; practices: PracticeArea[]; users: AdminUser[]; inquiries: Inquiry[]; smtp: SmtpSettings; emailTemplates: EmailTemplate[]; media: MediaAsset[] };
type Tab = "overview" | "site" | "services" | "lawyers" | "articles" | "media" | "inquiries" | "email" | "users";
type Modal = { kind: "lawyer"; item?: Lawyer } | { kind: "article"; item?: ArticleType } | { kind: "practice"; item?: PracticeArea } | { kind: "user"; item?: AdminUser } | { kind: "inquiry"; item: Inquiry } | null;
type SaveKind = "lawyers" | "articles" | "practices" | "users" | "inquiries";

const nav: [Tab, string, ElementType][] = [
  ["overview", "Resumen", LayoutDashboard], ["site", "Identidad y página", Settings], ["services", "Servicios legales", BriefcaseBusiness],
  ["lawyers", "Abogados", Users], ["articles", "Editorial", FileText], ["media", "Biblioteca multimedia", ImageIcon], ["inquiries", "Consultas", Inbox], ["email", "Correo SMTP", Mail], ["users", "Usuarios", Users],
];
const arrayText = (value: string[]) => value.join("; ");
const parseArray = (value: FormDataEntryValue | null) => String(value || "").split(";").map((item) => item.trim()).filter(Boolean);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("es-EC", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "—";
const datetimeLocal = (value: string | null) => { if (!value) return ""; const item = new Date(value); const pad = (part: number) => String(part).padStart(2, "0"); return `${item.getFullYear()}-${pad(item.getMonth() + 1)}-${pad(item.getDate())}T${pad(item.getHours())}:${pad(item.getMinutes())}`; };
const statusLabel: Record<Inquiry["status"], string> = { new: "Nueva", reviewed: "Revisada", scheduled: "Agendada", resolved: "Resuelta", rejected: "Rechazada" };

export function DashboardClient() {
  const [data, setData] = useState<DashboardData | null>(null); const [tab, setTab] = useState<Tab>("overview"); const [modal, setModal] = useState<Modal>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/data", { cache: "no-store" }); if (response.status === 401) { window.location.href = "/login"; return; } setData(await response.json()); }, []);
  useEffect(() => { load(); }, [load]);
  const counts = useMemo(() => data ? { published: data.articles.filter((item) => item.status === "published").length, drafts: data.articles.filter((item) => item.status === "draft").length, newInquiries: data.inquiries.filter((item) => item.status === "new").length } : null, [data]);
  const visibleNav = nav.filter(([id]) => data?.session.role !== "editor" || (id !== "email" && id !== "users"));

  async function api(url: string, options: RequestInit, success = "Cambios guardados.") {
    setBusy(true); setNotice(""); const response = await fetch(url, options); const result = await response.json().catch(() => ({}));
    if (!response.ok) { setNotice(result.error || "No fue posible guardar los cambios."); setBusy(false); return false; }
    await load(); setBusy(false); setNotice(success); return true;
  }
  async function upload(file: File, alt: string) { const body = new FormData(); body.set("file", file); body.set("alt_text", alt); const response = await fetch("/api/admin/media", { method: "POST", body }); const result = await response.json(); if (!response.ok) { setNotice(result.error || "No fue posible cargar la imagen."); return null; } return result as { id: string; url: string }; }
  async function remove(kind: "lawyers" | "articles" | "practices" | "users", id: string) { if (!confirm("¿Desea eliminar este registro? Esta acción no se puede deshacer.")) return; await api(`/api/admin/${kind}?id=${id}`, { method: "DELETE" }); }
  async function removeMedia(id: string) { if (!confirm("¿Eliminar esta imagen del sistema? Se retirará también de las secciones donde esté utilizada.")) return; await api(`/api/admin/media?id=${id}`, { method: "DELETE" }, "Imagen eliminada del sistema."); }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/login"; }
  if (!data) return <div style={{ minHeight: "100svh", display: "grid", placeItems: "center", background: "#101311", color: "#b9945a" }}><LoaderCircle className="animate-spin" size={30} /></div>;

  async function saveEditor(kind: SaveKind, payload: Record<string, unknown>, file?: File) {
    if (file) { const media = await upload(file, kind === "lawyers" ? String(payload.full_name) : String(payload.title)); if (!media) return; if (kind === "lawyers") payload.photo_media_id = media.id; if (kind === "articles") payload.cover_media_id = media.id; }
    const isInquiry = kind === "inquiries";
    if (await api(`/api/admin/${kind}`, { method: isInquiry ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }, isInquiry ? "Respuesta enviada y consulta actualizada." : "Cambios guardados.")) setModal(null);
  }

  return <div className="admin-layout">
    <aside className="admin-sidebar"><Link href="/" target="_blank"><BrandMark logoUrl={data.settings.logo_url} shortName={data.settings.short_name} /></Link><nav className="admin-nav">{visibleNav.map(([id, label, Icon]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><Icon size={17} /><span className="nav-label">{label}</span>{id === "inquiries" && counts && counts.newInquiries > 0 && <span className="badge live" style={{ marginLeft: "auto" }}>{counts.newInquiries}</span>}</button>)}</nav><div className="admin-sidebar-footer"><span style={{ fontSize: 10, opacity: .55, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{data.session.email}</span><button className="button-ghost" onClick={logout}><LogOut size={13} /><span>Cerrar sesión</span></button></div></aside>
    <main className="admin-main"><header className="admin-topbar"><div><h1>{visibleNav.find(([id]) => id === tab)?.[1] || "Panel"}</h1><p>{data.settings.firm_name} · Panel administrativo</p></div><div className="admin-actions"><Link href="/" target="_blank" className="button-light"><Eye size={14} /><span className="nav-label">Ver sitio</span></Link></div></header>
      {notice && <p className="form-status admin-notice" data-success={notice.includes("guardad") || notice.includes("enviad")}>{notice}</p>}
      {tab === "overview" && <Overview data={data} counts={counts!} setTab={setTab} />}
      {tab === "site" && <SettingsPanel data={data} busy={busy} upload={upload} save={async (payload) => { await api("/api/admin/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }} />}
      {tab === "services" && <ListPanel title="Servicios y áreas de práctica" action="Nuevo servicio" onAdd={() => setModal({ kind: "practice" })}><table className="admin-table"><thead><tr><th>Orden</th><th>Servicio</th><th>Descripción</th><th>Estado</th><th /></tr></thead><tbody>{data.practices.map((item) => <tr key={item.id}><td>{item.display_order}</td><td><strong>{item.title}</strong></td><td style={{ maxWidth: 430 }}>{item.description}</td><td><span className={`badge ${item.published ? "live" : ""}`}>{item.published ? "Publicado" : "Oculto"}</span></td><td><div className="admin-table-actions"><button className="icon-button" onClick={() => setModal({ kind: "practice", item })}><Pencil size={13} /></button><button className="icon-button" onClick={() => remove("practices", item.id)}><Trash2 size={13} /></button></div></td></tr>)}</tbody></table></ListPanel>}
      {tab === "lawyers" && <ListPanel title="Directorio profesional" action="Nuevo abogado" onAdd={() => setModal({ kind: "lawyer" })}><table className="admin-table"><thead><tr><th>Profesional</th><th>Especialidades</th><th>Estado</th><th /></tr></thead><tbody>{data.lawyers.map((item) => <tr key={item.id}><td><strong>{item.full_name}</strong><br /><span style={{ color: "#777" }}>{item.title}</span></td><td>{item.specialties.slice(0, 2).join(" · ")}</td><td><span className={`badge ${item.published ? "live" : ""}`}>{item.published ? "Publicado" : "Oculto"}</span></td><td><div className="admin-table-actions"><button className="icon-button" onClick={() => setModal({ kind: "lawyer", item })}><Pencil size={13} /></button><button className="icon-button" onClick={() => remove("lawyers", item.id)}><Trash2 size={13} /></button></div></td></tr>)}</tbody></table></ListPanel>}
      {tab === "articles" && <ListPanel title="Publicaciones" action="Nuevo artículo" onAdd={() => setModal({ kind: "article" })}><table className="admin-table"><thead><tr><th>Título</th><th>Categoría</th><th>Fecha</th><th>Estado</th><th /></tr></thead><tbody>{data.articles.map((item) => <tr key={item.id}><td><strong>{item.title}</strong></td><td>{item.category}</td><td>{date(item.published_at)}</td><td><span className={`badge ${item.status === "published" ? "live" : ""}`}>{item.status === "published" ? "Publicado" : "Borrador"}</span></td><td><div className="admin-table-actions"><button className="icon-button" onClick={() => setModal({ kind: "article", item })}><Pencil size={13} /></button><button className="icon-button" onClick={() => remove("articles", item.id)}><Trash2 size={13} /></button></div></td></tr>)}</tbody></table></ListPanel>}
      {tab === "media" && <MediaPanel media={data.media} canDelete={data.session.role !== "editor"} remove={removeMedia} />}
      {tab === "inquiries" && <ListPanel title="Solicitudes recibidas"><table className="admin-table"><thead><tr><th>Contacto</th><th>Asunto</th><th>Fecha</th><th>Estado</th><th /></tr></thead><tbody>{data.inquiries.map((item) => <tr key={item.id}><td><strong>{item.full_name}</strong><br /><a href={`mailto:${item.email}`} style={{ color: "var(--gold)" }}>{item.email}</a></td><td style={{ maxWidth: 340 }}><strong>{item.matter}</strong><br /><span style={{ color: "#777" }}>{item.message.slice(0, 110)}{item.message.length > 110 ? "…" : ""}</span></td><td>{date(item.created_at)}</td><td><span className={`badge inquiry-${item.status}`}>{statusLabel[item.status]}</span></td><td><button className="button-light" onClick={() => setModal({ kind: "inquiry", item })}><Mail size={13} /> Responder</button></td></tr>)}</tbody></table></ListPanel>}
      {tab === "email" && <EmailPanel data={data} busy={busy} saveSmtp={async (payload) => api("/api/admin/smtp", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }, "Configuración SMTP guardada.")} testSmtp={async (recipient) => api("/api/admin/smtp/test", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recipient }) }, "Correo de prueba enviado.")} saveTemplate={async (payload) => api("/api/admin/templates", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }, "Plantilla actualizada.")} />}
      {tab === "users" && <ListPanel title="Equipo administrativo" action={data.session.role === "owner" ? "Nuevo usuario" : undefined} onAdd={() => setModal({ kind: "user" })}><table className="admin-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Último acceso</th><th>Estado</th><th /></tr></thead><tbody>{data.users.map((item) => <tr key={item.id}><td><strong>{item.full_name}</strong><br /><span style={{ color: "#777" }}>{item.email}</span></td><td>{item.role}</td><td>{date(item.last_login_at)}</td><td><span className={`badge ${item.active ? "live" : ""}`}>{item.active ? "Activo" : "Inactivo"}</span></td><td>{data.session.role === "owner" && <div className="admin-table-actions"><button className="icon-button" onClick={() => setModal({ kind: "user", item })}><Pencil size={13} /></button>{item.id !== data.session.userId && <button className="icon-button" onClick={() => remove("users", item.id)}><Trash2 size={13} /></button>}</div>}</td></tr>)}</tbody></table></ListPanel>}
    </main>
    {modal && <EditorModal modal={modal} lawyers={data.lawyers} busy={busy} close={() => setModal(null)} save={saveEditor} />}
  </div>;
}

function Overview({ data, counts, setTab }: { data: DashboardData; counts: { published: number; drafts: number; newInquiries: number }; setTab: (tab: Tab) => void }) {
  const stats = [[data.lawyers.length, "Perfiles de abogados", Users], [data.practices.length, "Servicios legales", BriefcaseBusiness], [counts.published, "Artículos publicados", FileText], [counts.newInquiries, "Consultas nuevas", Inbox]] as const;
  return <><div className="stat-grid">{stats.map(([value, label, Icon]) => <div className="stat-card" key={label}><Icon size={17} color="var(--gold)" /><strong>{value}</strong><span>{label}</span></div>)}</div><div className="admin-panel"><div className="admin-section-head"><h2>Actividad reciente</h2><button className="button-light" onClick={() => setTab("inquiries")}>Ver consultas <ChevronRight size={13} /></button></div>{data.inquiries.length === 0 ? <div className="tab-empty">Aún no se han recibido solicitudes.</div> : <table className="admin-table"><tbody>{data.inquiries.slice(0, 5).map((item) => <tr key={item.id}><td><strong>{item.full_name}</strong><br /><span style={{ color: "#777" }}>{item.matter}</span></td><td>{date(item.created_at)}</td><td><span className={`badge inquiry-${item.status}`}>{statusLabel[item.status]}</span></td></tr>)}</tbody></table>}</div></>;
}

function ListPanel({ title, action, onAdd, children }: { title: string; action?: string; onAdd?: () => void; children: ReactNode }) { return <section className="admin-panel"><div className="admin-section-head"><h2>{title}</h2>{action && <button className="button-primary" onClick={onAdd}><Plus size={14} />{action}</button>}</div>{children}</section>; }

function MediaPanel({ media, canDelete, remove }: { media: MediaAsset[]; canDelete: boolean; remove: (id: string) => Promise<void> }) {
  return <section className="admin-panel"><div className="admin-section-head"><div><h2>Biblioteca multimedia</h2><p className="panel-description">Controle las imágenes cargadas y conozca dónde siguen en uso.</p></div><span className="badge">{media.length} archivos</span></div>{media.length === 0 ? <div className="tab-empty">Aún no existen imágenes cargadas.</div> : <div className="media-library">{media.map((asset) => <article className="media-admin-card" key={asset.id}><div className="media-admin-preview"><img src={asset.url} alt={asset.alt_text || asset.filename} /></div><div className="media-admin-info"><strong title={asset.filename}>{asset.filename}</strong><span>{(asset.size_bytes / 1024).toFixed(0)} KB · {asset.provider === "supabase-storage" ? "Supabase Storage" : "PostgreSQL"}</span><span className={`badge ${asset.usage_count > 0 ? "live" : ""}`}>{asset.usage_count > 0 ? `En uso: ${asset.usage_count}` : "Sin usar"}</span>{canDelete && <button className="button-light danger-button" onClick={() => remove(asset.id)}><Trash2 size={13} /> Eliminar</button>}</div></article>)}</div>}</section>;
}

function SettingsPanel({ data, busy, upload, save }: { data: DashboardData; busy: boolean; upload: (file: File, alt: string) => Promise<{ id: string; url: string } | null>; save: (payload: Record<string, unknown>) => Promise<void> }) {
  const settings = data.settings;
  async function submit(form: FormData) {
    let logoUrl = form.get("remove_logo") === "on" ? null : settings.logo_url;
    let logoMediaId = form.get("remove_logo") === "on" ? null : settings.logo_media_id;
    let aboutMediaId = form.get("remove_about_image") === "on" ? null : settings.about_image_media_id;
    const logoFile = form.get("logo_file");
    if (logoFile instanceof File && logoFile.size > 0) { const media = await upload(logoFile, `Logotipo ${settings.short_name}`); if (!media) return; logoUrl = media.url; logoMediaId = media.id; }
    const aboutFile = form.get("about_file");
    if (aboutFile instanceof File && aboutFile.size > 0) { const media = await upload(aboutFile, `Imagen institucional ${settings.short_name}`); if (!media) return; aboutMediaId = media.id; }
    const payload = Object.fromEntries(form) as Record<string, unknown>;
    for (const field of ["logo_file", "about_file", "remove_logo", "remove_about_image"]) delete payload[field];
    payload.logo_url = logoUrl; payload.logo_media_id = logoMediaId; payload.about_image_media_id = aboutMediaId;
    await save(payload);
  }
  return <form className="admin-panel admin-form" action={submit}>
    <div className="admin-subsection-title full"><span>01</span><div><h2>Identidad de marca</h2><p>Se aplica al sitio, login, PWA y correos.</p></div></div>
    <div className="field full logo-upload-card"><div className="logo-preview-dark"><BrandMark logoUrl={settings.logo_url} shortName={settings.short_name} /></div><div><label>Logotipo del estudio</label><p>Suba PNG, WEBP o JPG con fondo transparente.</p><input name="logo_file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" />{settings.logo_url && <label className="check-field remove-image-check"><input type="checkbox" name="remove_logo" /> Quitar logo actual</label>}</div></div>
    <div className="field"><label>Nombre completo del estudio</label><input name="firm_name" defaultValue={settings.firm_name} required /></div><div className="field"><label>Nombre corto</label><input name="short_name" defaultValue={settings.short_name} required /></div><div className="field full"><label>Rótulo superior</label><input name="eyebrow" defaultValue={settings.eyebrow} /></div><div className="field full"><label>Titular principal</label><input name="hero_title" defaultValue={settings.hero_title} required /></div><div className="field full"><label>Descripción principal</label><textarea name="hero_description" defaultValue={settings.hero_description} /></div>
    <div className="admin-subsection-title full"><span>02</span><div><h2>Quiénes somos</h2><p>Contenido editorial e imagen institucional.</p></div></div>
    <div className="field"><label>Rótulo de sección</label><input name="about_eyebrow" defaultValue={settings.about_eyebrow} /></div><div className="field"><label>Título de presentación</label><input name="about_title" defaultValue={settings.about_title} /></div><div className="field full"><label>Historia y presentación</label><textarea name="about_text" defaultValue={settings.about_text} style={{ minHeight: 180 }} /></div><div className="field full image-control-card">{settings.about_image_media_id && <img src={`/api/media/${settings.about_image_media_id}`} alt="Imagen institucional actual" />}<div><label><Upload size={13} /> Imagen de Quiénes somos</label><input name="about_file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" />{settings.about_image_media_id && <label className="check-field remove-image-check"><input type="checkbox" name="remove_about_image" /> Quitar imagen actual</label>}</div></div>
    <div className="admin-subsection-title full"><span>03</span><div><h2>Contacto y ubicación</h2><p>Datos públicos y mapa embebido.</p></div></div>
    <div className="field"><label>Correo</label><input name="email" type="email" defaultValue={settings.email} /></div><div className="field"><label>Teléfono</label><input name="phone" defaultValue={settings.phone} /></div><div className="field"><label>WhatsApp</label><input name="whatsapp" defaultValue={settings.whatsapp} /></div><div className="field"><label>Dirección / atención</label><input name="address" defaultValue={settings.address} /></div><div className="field"><label>Título del mapa</label><input name="map_title" defaultValue={settings.map_title} /></div><div className="field full"><label><MapPin size={13} /> URL o iframe de Google Maps</label><textarea name="map_embed_url" defaultValue={settings.map_embed_url} placeholder="Pegue el código iframe o su URL HTTPS" /></div>
    <div className="admin-subsection-title full"><span>04</span><div><h2>Apariencia y redes</h2><p>Colores institucionales y canales sociales.</p></div></div>
    <div className="field"><label>Color principal</label><input name="primary_color" type="color" defaultValue={settings.primary_color} /></div><div className="field"><label>Color complementario</label><input name="accent_color" type="color" defaultValue={settings.accent_color} /></div><div className="field"><label>Instagram</label><input name="instagram" defaultValue={settings.instagram} /></div><div className="field"><label>LinkedIn</label><input name="linkedin" defaultValue={settings.linkedin} /></div><div className="admin-form-actions"><button className="button-primary" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" size={14} /> : <Save size={14} />} Guardar toda la configuración</button></div>
  </form>;
}

function EmailPanel({ data, busy, saveSmtp, testSmtp, saveTemplate }: { data: DashboardData; busy: boolean; saveSmtp: (payload: Record<string, unknown>) => Promise<boolean>; testSmtp: (recipient: string) => Promise<boolean>; saveTemplate: (payload: Record<string, unknown>) => Promise<boolean> }) {
  const smtp = data.smtp;
  async function save(form: FormData) { await saveSmtp({ host: form.get("host"), port: Number(form.get("port")), secure: form.get("secure") === "on", username: form.get("username"), password: form.get("password") || undefined, from_name: form.get("from_name"), from_email: form.get("from_email"), reply_to: form.get("reply_to"), enabled: form.get("enabled") === "on" }); }
  async function test(form: FormData) { await testSmtp(String(form.get("recipient"))); }
  return <div className="email-admin-grid"><form className="admin-panel admin-form" action={save}><div className="admin-section-head full"><div><h2>Servidor SMTP</h2><p className="panel-description">Las contraseñas se cifran antes de guardarse.</p></div><span className={`badge ${smtp.enabled ? "live" : ""}`}>{smtp.enabled ? "Activo" : "Inactivo"}</span></div><div className="field"><label>Servidor</label><input name="host" placeholder="smtp.gmail.com" defaultValue={smtp.host} /></div><div className="field"><label>Puerto</label><input name="port" type="number" defaultValue={smtp.port || 587} /></div><div className="field"><label>Usuario SMTP</label><input name="username" defaultValue={smtp.username} autoComplete="username" /></div><div className="field"><label>Contraseña {smtp.has_password ? "(guardada)" : ""}</label><input name="password" type="password" placeholder={smtp.has_password ? "••••••••••••" : "Contraseña o App Password"} autoComplete="new-password" /></div><div className="field"><label>Nombre del remitente</label><input name="from_name" defaultValue={smtp.from_name || data.settings.firm_name} /></div><div className="field"><label>Correo remitente</label><input name="from_email" type="email" defaultValue={smtp.from_email} /></div><div className="field full"><label>Responder a</label><input name="reply_to" type="email" defaultValue={smtp.reply_to || data.settings.email} /></div><label className="check-field"><input type="checkbox" name="secure" defaultChecked={smtp.secure} /> SSL directo (normalmente puerto 465)</label><label className="check-field"><input type="checkbox" name="enabled" defaultChecked={smtp.enabled} /> Activar correos automáticos</label><div className="admin-form-actions"><button className="button-primary" disabled={busy}><Save size={14} /> Guardar SMTP</button></div></form><form className="admin-panel smtp-test-card" action={test}><Mail size={28} color="var(--gold)" /><h3>Probar configuración</h3><p>Envíe un correo real para comprobar servidor, credenciales y remitente.</p><div className="field"><label>Destinatario de prueba</label><input name="recipient" type="email" defaultValue={data.session.email} required /></div><button className="button-light" disabled={busy}>Enviar prueba</button></form><section className="admin-panel templates-panel"><div className="admin-section-head"><div><h2>Respuestas preestablecidas</h2><p className="panel-description">Edite el asunto y el contenido base de cada notificación.</p></div></div><div className="template-grid">{data.emailTemplates.map((template) => <TemplateForm key={template.template_key} template={template} busy={busy} save={saveTemplate} />)}</div></section></div>;
}

function TemplateForm({ template, busy, save }: { template: EmailTemplate; busy: boolean; save: (payload: Record<string, unknown>) => Promise<boolean> }) { async function submit(form: FormData) { await save({ template_key: template.template_key, subject: form.get("subject"), heading: form.get("heading"), message: form.get("message") }); } const names = { received: "Recepción automática", scheduled: "Cita agendada", resolved: "Atendida / resuelta", rejected: "Declinación formal" }; return <form className="template-card" action={submit}><span className="eyebrow" style={{ color: "var(--gold)" }}>{names[template.template_key]}</span><div className="field"><label>Asunto</label><input name="subject" defaultValue={template.subject} /></div><div className="field"><label>Titular</label><input name="heading" defaultValue={template.heading} /></div><div className="field"><label>Mensaje base</label><textarea name="message" defaultValue={template.message} /></div><button className="button-light" disabled={busy}><Save size={13} /> Guardar plantilla</button></form>; }

function EditorModal({ modal, lawyers, busy, close, save }: { modal: Exclude<Modal, null>; lawyers: Lawyer[]; busy: boolean; close: () => void; save: (kind: SaveKind, payload: Record<string, unknown>, file?: File) => Promise<void> }) {
  async function submit(form: FormData) { const file = form.get("photo") instanceof File && (form.get("photo") as File).size > 0 ? form.get("photo") as File : undefined; if (modal.kind === "lawyer") { const item = modal.item; await save("lawyers", { id: item?.id, slug: String(form.get("slug") || ""), full_name: form.get("full_name"), title: form.get("title"), summary: form.get("summary"), bio: form.get("bio"), specialties: parseArray(form.get("specialties")), education: parseArray(form.get("education")), languages: parseArray(form.get("languages")), bar_admissions: parseArray(form.get("bar_admissions")), highlights: String(form.get("highlights") || "").split("\n").filter(Boolean).map((line) => { const [title, ...description] = line.split("|"); return { title: title.trim(), description: description.join("|").trim() }; }), email: form.get("email"), phone: form.get("phone"), photo_media_id: form.get("remove_photo") === "on" ? null : item?.photo_media_id || null, featured: form.get("featured") === "on", published: form.get("published") === "on", display_order: Number(form.get("display_order") || 0) }, file); } else if (modal.kind === "article") { const item = modal.item; await save("articles", { id: item?.id, slug: form.get("slug"), title: form.get("title"), excerpt: form.get("excerpt"), content: form.get("content"), category: form.get("category"), status: form.get("status"), featured: form.get("featured") === "on", author_lawyer_id: form.get("author_lawyer_id") || null, cover_media_id: form.get("remove_photo") === "on" ? null : item?.cover_media_id || null }, file); } else if (modal.kind === "practice") { const item = modal.item; await save("practices", { id: item?.id, slug: form.get("slug"), title: form.get("title"), description: form.get("description"), icon: "scale", display_order: Number(form.get("display_order") || 0), published: form.get("published") === "on" }); } else if (modal.kind === "user") { const item = modal.item; await save("users", { id: item?.id, full_name: form.get("full_name"), email: form.get("email"), password: form.get("password") || undefined, role: form.get("role"), active: form.get("active") === "on" }); } else { const status = String(form.get("status")); const localDate = String(form.get("scheduled_at") || ""); await save("inquiries", { id: modal.item.id, status, scheduled_at: localDate ? new Date(localDate).toISOString() : null, resolution_notes: String(form.get("resolution_notes") || "") }); } }
  const title = modal.kind === "inquiry" ? "Responder consulta" : `${modal.item ? "Editar" : "Crear"} ${modal.kind === "lawyer" ? "abogado" : modal.kind === "article" ? "artículo" : modal.kind === "practice" ? "servicio" : "usuario"}`;
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><div className="admin-section-head"><h2>{title}</h2><button className="icon-button" onClick={close}><X size={16} /></button></div><form className="admin-form" action={submit}>{modal.kind === "lawyer" && <LawyerFields item={modal.item} />}{modal.kind === "article" && <ArticleFields item={modal.item} lawyers={lawyers} />}{modal.kind === "practice" && <PracticeFields item={modal.item} />}{modal.kind === "user" && <UserFields item={modal.item} />}{modal.kind === "inquiry" && <InquiryFields item={modal.item} />}<div className="admin-form-actions"><button type="button" className="button-light" onClick={close}>Cancelar</button><button className="button-primary" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" size={14} /> : modal.kind === "inquiry" ? <Mail size={14} /> : <Save size={14} />} {modal.kind === "inquiry" ? "Aplicar y notificar" : "Guardar"}</button></div></form></div></div>;
}

function LawyerFields({ item }: { item?: Lawyer }) { return <><div className="field"><label>Nombre completo</label><input name="full_name" defaultValue={item?.full_name || ""} required /></div><div className="field"><label>Cargo</label><input name="title" defaultValue={item?.title || "Abogado"} /></div><div className="field"><label>Slug URL</label><input name="slug" defaultValue={item?.slug || ""} placeholder="se genera automáticamente" /></div><div className="field"><label>Orden</label><input name="display_order" type="number" defaultValue={item?.display_order || 0} /></div><div className="field full"><label>Resumen</label><textarea name="summary" defaultValue={item?.summary || ""} /></div><div className="field full"><label>Biografía</label><textarea name="bio" defaultValue={item?.bio || ""} style={{ minHeight: 180 }} /></div><div className="field full"><label>Especialidades (separadas por ;)</label><input name="specialties" defaultValue={arrayText(item?.specialties || [])} /></div><div className="field full"><label>Formación (separada por ;)</label><input name="education" defaultValue={arrayText(item?.education || [])} /></div><div className="field"><label>Idiomas (separados por ;)</label><input name="languages" defaultValue={arrayText(item?.languages || [])} /></div><div className="field"><label>Colegiatura (separada por ;)</label><input name="bar_admissions" defaultValue={arrayText(item?.bar_admissions || [])} /></div><div className="field full"><label>Destacados (uno por línea: título | descripción)</label><textarea name="highlights" defaultValue={(item?.highlights || []).map((highlight) => `${highlight.title} | ${highlight.description}`).join("\n")} /></div><div className="field"><label>Correo</label><input name="email" type="email" defaultValue={item?.email || ""} /></div><div className="field"><label>Teléfono</label><input name="phone" defaultValue={item?.phone || ""} /></div><div className="field full image-control-card">{item?.photo_media_id && <img src={`/api/media/${item.photo_media_id}`} alt={`Fotografía actual de ${item.full_name}`} />}<div><label><Upload size={13} /> Fotografía profesional (máx. 5 MB)</label><input name="photo" type="file" accept="image/jpeg,image/png,image/webp,image/avif" />{item?.photo_media_id && <label className="check-field remove-image-check"><input type="checkbox" name="remove_photo" /> Quitar fotografía actual</label>}</div></div><label className="check-field"><input type="checkbox" name="featured" defaultChecked={item?.featured} /> Perfil destacado</label><label className="check-field"><input type="checkbox" name="published" defaultChecked={item?.published ?? true} /> Publicado</label></>; }
function ArticleFields({ item, lawyers }: { item?: ArticleType; lawyers: Lawyer[] }) { return <><div className="field full"><label>Título</label><input name="title" defaultValue={item?.title || ""} required /></div><div className="field"><label>Slug URL</label><input name="slug" defaultValue={item?.slug || ""} /></div><div className="field"><label>Categoría</label><input name="category" defaultValue={item?.category || "Análisis"} /></div><div className="field full"><label>Extracto</label><textarea name="excerpt" defaultValue={item?.excerpt || ""} /></div><div className="field full"><label>Contenido (use ## para subtítulos)</label><textarea name="content" defaultValue={item?.content || ""} style={{ minHeight: 260 }} /></div><div className="field"><label>Autor</label><select name="author_lawyer_id" defaultValue={item?.author_lawyer_id || ""}><option value="">Estudio Jurídico</option>{lawyers.map((lawyer) => <option value={lawyer.id} key={lawyer.id}>{lawyer.full_name}</option>)}</select></div><div className="field"><label>Estado</label><select name="status" defaultValue={item?.status || "draft"}><option value="draft">Borrador</option><option value="published">Publicado</option></select></div><div className="field full image-control-card">{item?.cover_media_id && <img src={`/api/media/${item.cover_media_id}`} alt={`Portada actual de ${item.title}`} />}<div><label><Upload size={13} /> Imagen de portada (máx. 5 MB)</label><input name="photo" type="file" accept="image/jpeg,image/png,image/webp,image/avif" />{item?.cover_media_id && <label className="check-field remove-image-check"><input type="checkbox" name="remove_photo" /> Quitar portada actual</label>}</div></div><label className="check-field"><input type="checkbox" name="featured" defaultChecked={item?.featured} /> Artículo destacado</label></>; }
function PracticeFields({ item }: { item?: PracticeArea }) { return <><div className="field full"><label>Nombre del servicio</label><input name="title" defaultValue={item?.title || ""} required /></div><div className="field"><label>Slug URL</label><input name="slug" defaultValue={item?.slug || ""} /></div><div className="field"><label>Orden</label><input name="display_order" type="number" defaultValue={item?.display_order || 0} /></div><div className="field full"><label>Descripción</label><textarea name="description" defaultValue={item?.description || ""} style={{ minHeight: 150 }} required /></div><label className="check-field"><input type="checkbox" name="published" defaultChecked={item?.published ?? true} /> Publicado</label></>; }
function UserFields({ item }: { item?: AdminUser }) { return <><div className="field"><label>Nombre completo</label><input name="full_name" defaultValue={item?.full_name || ""} required /></div><div className="field"><label>Correo</label><input name="email" type="email" defaultValue={item?.email || ""} required /></div><div className="field"><label>Contraseña {item ? "(dejar vacía para conservar)" : ""}</label><input name="password" type="password" minLength={item ? 0 : 10} required={!item} /></div><div className="field"><label>Rol</label><select name="role" defaultValue={item?.role || "editor"}><option value="editor">Editor</option><option value="admin">Administrador</option><option value="owner">Propietario</option></select></div><label className="check-field"><input type="checkbox" name="active" defaultChecked={item?.active ?? true} /> Usuario activo</label></>; }

function InquiryFields({ item }: { item: Inquiry }) { const [status, setStatus] = useState<"reviewed" | "scheduled" | "resolved" | "rejected">(item.status === "new" ? "reviewed" : item.status === "scheduled" || item.status === "resolved" || item.status === "rejected" || item.status === "reviewed" ? item.status : "reviewed"); return <><div className="inquiry-summary full"><span className="eyebrow" style={{ color: "var(--gold)" }}>{item.matter}</span><h3>{item.full_name}</h3><p>{item.message}</p><a href={`mailto:${item.email}`}>{item.email}</a>{item.phone && <span>{item.phone}</span>}</div><div className="field full"><label>Respuesta preestablecida</label><select name="status" value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="reviewed">Solo marcar como revisada</option><option value="scheduled">Agendada · enviar fecha y hora</option><option value="resolved">Atendida / resuelta · enviar observaciones</option><option value="rejected">Rechazada · enviar declinación formal</option></select></div>{status === "scheduled" && <div className="field full"><label><CalendarDays size={13} /> Fecha y hora de la cita</label><input name="scheduled_at" type="datetime-local" required defaultValue={datetimeLocal(item.scheduled_at)} /></div>}{(status === "resolved" || status === "rejected") && <div className="field full"><label>{status === "resolved" ? "Observaciones finales" : "Motivo o recomendación cortés"}</label><textarea name="resolution_notes" defaultValue={item.resolution_notes} style={{ minHeight: 150 }} required /></div>}{status !== "reviewed" && <p className="mail-warning full"><Mail size={15} /> Al guardar se enviará inmediatamente un correo HTML al cliente.</p>}</>; }
